spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?useSSL=false&useUnicode=true&characterEncoding=utf-8&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 'admin'
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
  #    pool:
  #      max-idle: 500
  #      min-idle: 50
  #      max-active: 2000
  #      max-wait: 1000
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true       #SQL显示
server:
  port: 8081
